tempProject/basicApp/urls.py
from django.conf.urls import url
from basicApp import views

#for template tagging
app_name = 'basicApp'

urlpatterns = [
    url(r'^other/$',views.other,name='other'),
    url(r'^relative/$',views.relative,name='relative'),
]

tempProject/tempProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basicApp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    #url(r'^other/',views.other,name='other'),
    url(r'^basicApp/',include('basicApp.urls'))
    #url(r'^relative/',views.relative,name='relative'),
]

tempProject/basicApp/models.py
from django.db import models

# Create your models here.

tempProject/basicApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dic={'text':'hello world','number': 100,}
    return render(request,'basicApp/index.html',context_dic)

def other(request):
    return render (request,'basicApp/other.html')

def relative(request):
    return render (request,'basicApp/relative.html')

tempProject/templates/basicApp/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light mr-auto">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basicApp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {# anything outside this block is inherited when extended #}
      {% endblock %}
    </div>
  </body>
</html>

tempProject/templates/basicApp/index.html
<!DOCTYPE html>

{% extends "basicApp/base.html" %}
{% load extra %} #check templatetags/extra.py

  {% block body_block %}
    <h1>welcome to Home page</h1>
    <h3>this is an example</h3>
    <h3>{{ text | cut_str:'hello' }}</h3>
    <h3>{{ number | add:"10"}}</h3>
  {% endblock %}

tempProject/templates/basicApp/other.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}

  {% block body_block %}
    <h1>welcome to other page</h1>
    <h3>this is an example</h3>
  {% endblock %}

tempProject/templates/basicApp/relative.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welcome to relative</h1>
    <a href="{% url 'basicApp:other' %}">go to other page</a>
    <p></p>
    <a href="{% url 'admin:index' %}">go to admin page</a>
    <p></p>
    <a href="{% url 'index' %}">main page</a>
  </body>
</html>